/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pkg.exoad.omni;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       OmniMainp classUnderTest = newOmniMainp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
